### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by Mab306** [joBr99/nspanel-lovelace-ui#1038]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:

![Screenshot_20231117_080247_Chrome](https://github.com/joBr99/nspanel-lovelace-ui/assets/114089256/c79f5ec9-c080-445a-be94-99f1a272e61b)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

![Screenshot_20231117_080434_Home Assistant](https://github.com/joBr99/nspanel-lovelace-ui/assets/114089256/80f41ea3-ac40-49d9-aa12-96e4beb5231b)


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
![Screenshot_20231117_080450_Home Assistant](https://github.com/joBr99/nspanel-lovelace-ui/assets/114089256/57e96e63-2d31-43df-ac57-67ac0f1b1b62)


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

![Screenshot_20231117_120934_Home Assistant](https://github.com/joBr99/nspanel-lovelace-ui/assets/114089256/60704445-a990-4209-b62b-6a09df25e933)

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
Hey with appdaemon addon version 15 appdaemon.yaml move to a different directory and you can no longer edit it with the file editor

**Comment by joBr99** [comment]
You can use vs code to edit it it's now located at /addons_configs/a0d7b954_appdaemon

**Comment by AxelEichhoff** [comment]
On the way to solve the same problem the appdeamon did not start because:

[16:55:43] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
ERROR Error loading secrets file: /config/secrets.yaml
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[16:55:46] INFO: Service AppDaemon exited with code 1 (by signal 0)

**Comment by joBr99** [comment]
please follow the instructions here:

https://github.com/joBr99/nspanel-lovelace-ui/issues/1029

**Comment by AxelEichhoff** [comment]
YES. Just done. Thanks a lot.
Here is it written: https://docs.nspanel.pky.eu/configure_mqtt/

**Comment by Mab306** [comment]
Thanks it works now
