### ISSUE TITLE
[Task] Change delimiter in commands to nextion screen

### ISSUE THREAD

**Issue by marcbaro** [joBr99/nspanel-lovelace-ui#108]
First, congrats for this great work. It fits perfect with my needs for this device.
But i have an issue with alarm card.

De homeassistant json translation in catalan for the alarm texts contains commas. 

            "alarm_control_panel": {
                "arm_away": "Activar, fora",
                "arm_custom_bypass": "Bypass personalitzat",
                "arm_home": "Activar, a casa",
                "arm_night": "Activar, nocturn",
                "arm_vacation": "Activa en mode vacances",
                "clear_code": "Borrar",
                "code": "Codi",
                "disarm": "Desactivar"
            },

This causes the parse of the text string to the nspanel doesen't match. Texts and commands are shifted due to extra commas.

![MQTT](https://user-images.githubusercontent.com/25787241/161253109-b6dbcf6f-ae6a-4567-81c6-84f647a0c08f.png)

And the displays shows as

![20220401_130759](https://user-images.githubusercontent.com/25787241/161254845-0227e40b-7e42-422d-8d3e-7b7c9a508505.jpg)

Maybe if you could put the texts in quotes it would solve the problem

**Comment by joBr99** [comment]
Hey,
quoting won't help, using "," as delimiter was fine for the first card in the project, but it tuned out as a bad design design for other pages like the screensaver where I changed the delimiter after the first ",".

Maybe it's a good point to start changeing the delimiter to something that's normally not in the data.

**Comment by joBr99** [comment]
@marcbaro 
I've changed the delmiter in all commands to the screen from "," to "~" with https://github.com/joBr99/nspanel-lovelace-ui/commit/7f3a0d257e48883b8cf7873df49ae809eae74199 this should solve your problem.

You can upgrade to the development version to test this, since I changed all commands on all pages, this might have side effects  and needs some testing.

https://github.com/joBr99/nspanel-lovelace-ui#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by marcbaro** [comment]
Hi, now cardAlarm works fine. Many thanks!  :)
