### ISSUE TITLE
[BUG] Error while initial flashing tft file

### ISSUE THREAD

**Issue by duhow** [joBr99/nspanel-lovelace-ui#1224]
### PROBLEM DESCRIPTION

On Tasmota 12.5.0 (EU) and 14.0.0 (US), after configuring the device and start to run `FlashNexion`, the following error appeared, `USART` received 0 bytes, and the screen got stuck.

```
20:36:44.756 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
20:36:45.932 FLH: Send (High Speed) flash start
20:36:46.385 BRY: Exception> 'type_error' - unsupported operand type(s) for <: 'nil' and 'int'
```

Current autoexec.be file is https://github.com/joBr99/nspanel-lovelace-ui/blob/252339d36c4adf3a76d154fba02a608ea5cb4726/tasmota/autoexec.be

**Comment by joBr99** [comment]
Is your tasmota device able to access the Internet? (Gateway, DNS Server, etc)

**Comment by Meskalito1984** [comment]
Hello everyone,

I'm using this thread because I unfortunately also have a problem with the flash of the TFT file. The upload regularly crashes between 10 - 20%. 

My pannel is running Tasmota 14.0.0.1 and I host the tft file on my computer with a Python http server. I control this directly with the IP. As "autoexec.be" I tried the current one from the Github, as well as the procedure in the instructions: 

[](https://docs.nspanel.pky.eu/stable/prepare_nspanel/#configure-tasmota-template-for-nspanel)

I don't get an error message in the Tasmota console, but I do get an error message in the Phyton script:

  

> File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 840, in write
>     self._sock.sendall(b)
> ConnectionResetError: [WinError 10054] An existing connection was closed by the remote host
> 

I would be grateful for any troubleshooting ideas

**Comment by joBr99** [comment]
Hey, please do not use the python webserver, it doesn't support all http instructions - please use nginx, apache instead or use the url provied in the documentation.

**Comment by Meskalito1984** [comment]
Thanks for the tip. Unfortunately, the error behavior with the URL update is the same as in the instructions. 

However, I also have the impression that tasmota is not working properly on the nspanel. It often happens that controlling via the web terminal does not work and the panel seems to freeze. I do not know this kind of behavior from my other tasmota devices (e.g. Shelly switches).

**Comment by joBr99** [comment]
No, that's not normal do you have a bad wifi signal?

**Comment by Meskalito1984** [comment]
no, my signal strength is: RSSI 64%, -68 dBm I also had the panel right next to the router, unfortunately also without result

**Comment by Meskalito1984** [comment]
I was able to solve the problem. It was probably due to tasmota. 

After deleting the ESP again and flashing tasmota, the TFT OTA update worked on the first attempt. 

However, I cannot explain what went wrong with tasmota, I have never had such a problem before when flashing with the serial adapter
