### ISSUE TITLE
[Feature Request] More Colors for Icons on Screensaver

### ISSUE THREAD

**Issue by patricknitsch** [joBr99/nspanel-lovelace-ui#1229]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

On my screensaver I have Icons for my devices. The color changes, if the device goes on or off. Additionally I want to change the color, if the device is running or not. 

I tested it with the following command: 

`ScreensaverEntityIconColor: getState('esphome.0.48551917BA07.Sensor.1144390574.state').val > 5 ? Red : Blue,`

After reloading the panel it works, but it doesn't change the color during use.

Is it possible to implement it?

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

EU, Firmware 4.3.3.43

**Comment by Armilar** [comment]
The section for defining the entities is only loaded when the script starts, so a "getState" is not helpful as it is only a definition and not a trigger.
This means that a “getState” only has an effect at startup.
A trigger fires later in runtime when a data point changes.

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/102996011/09df8e59-5485-4bd4-ad39-b250bef1c6e6)

In order to still get a result, you can either, as in the example shown above:
- use the val_min, val_max, val_best method (green, yellow, red)
- define a desired color through the ioBroker and use it like a waste alias.

Wiki: https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-Config-Screensaver

**Comment by patricknitsch** [comment]
@Armilar: That was the trick! With seperate datapoints it works perfect. I red the doc for Screensaver but not good enough :)
Thank you!!
