### ISSUE TITLE
cover/curtain direction arrows on Cover entity

### ISSUE THREAD

**Issue by hatran0884** [joBr99/nspanel-lovelace-ui#139]
Hi

firstly, it is actually not an issue of the cover entity showing on NSPanel but it is just  a problem that i have with my cover having a button of UP direction greyed out in my HA Dashboard, i have spent alot of time trying to fix it without success . but i have no idea, when it shows in NSPanel, surprisingly all buttons (Up, Down, Stop buttons) no longer are greyed out. all can be controlled perfectly. 

so i wonder if you have done smt special to make it work that well ? 
fyi, i am having a Tuya wifi-based curtain and am using Local Tuya integration to integrate it in HA.

**Comment by joBr99** [comment]
lol, no clue why it's grayed out in HA, but I can at least tell you what I'm doing

so I cannot disable or grey the buttons, mainly because I didn't care, I guess it would be possible to implement it

the backend is calling the HA servcies, you can try them out in the development tab

![image](https://user-images.githubusercontent.com/29555657/163014094-e479b1da-d9a6-42f9-8a41-74f7a4588f22.png)

if you send me the number at supported features I can probably tell you a bit more about what HA thinks your cover can do and cannot do

![image](https://user-images.githubusercontent.com/29555657/163014361-38506e24-8cbe-41ee-a249-c9335ab732c9.png)

**Comment by hatran0884** [comment]
Here is my number at supported features: 

![image](https://user-images.githubusercontent.com/58875735/163015154-42c8f33e-301a-4b0d-a7b0-6cff5a898638.png)

let me know if you could find a solution for it

**Comment by joBr99** [comment]
Okay without looking into the HA source, since you have the same number I have, there is no difference in the supported features of the entity, so this isn't causing this.

Try calling the service and see what it does

**Comment by joBr99** [comment]
Yeah, no clue ask on the Homeassistent discord, (calling services is working working, but UI elements are disabled) 
In the worst case you can probably define custom buttons as a workaround that are calling the services you want.

**Comment by joBr99** [comment]
Wait is it only the up direction that is not working?

**Comment by hatran0884** [comment]
yes, only UP direction not working, position value is synced well with Tuya SmartLife App.

**Comment by hatran0884** [comment]
i have found a workaround by adding this line in customize.yaml: 

cover.curtain_5:
  assumed_state: true

basically, using it, HA will skip checking the actual position of the cover, so the UP and Down Button will always show up no matter the cover opens or closes.

**Comment by hatran0884** [comment]
if i slide the position slider to for example 80%, it will move to that correct position of 80% and the slider will keep in that position. . But if i use the UP and Down Button to move the cover, the position slider will not go accordingly. 
thanks a lot for your support!
