### ISSUE TITLE
[Bug] CRC sent by the display is wrong

### ISSUE THREAD

**Issue by sairon** [joBr99/nspanel-lovelace-ui#160]
With the message protocol change introduced in 49c587745822152c925a7559e247cc2d2de7a92c, the CRC sent by the display is wrong, since one byte is omitted from the CRC calculation. Seems that it could be fixed by changing a single line - though on all places that calculate the CRC - e.g. here:
https://github.com/joBr99/nspanel-lovelace-ui/blob/7bb27429263bf5c12608f4942fec6e718b56e552/HMI/n2t-out/screensaver.txt#L667
to `crcputs sys0,2`.

**Comment by joBr99** [comment]
fixed in EU and US-L Version

@jmbinette I replaced all occurences of `crcputs sys0,1` with `crcputs sys0,2`

Use the following commands to get an idea where `crcputs sys0,1` is in the US-P version.

`grep -R 'crcputs sys0,1' HMI/US/portrait/n2t-out/*`

`grep -C 7 -R 'crcputs sys0,1' HMI/US/portrait/n2t-out/*`

**Comment by sairon** [comment]
I don't use all possible pages but I'm not encountering warnings on incorrect checksum anymore with latest EU tft file. Thanks! :+1:
