### ISSUE TITLE
play audio/rttl on internal speaker

### ISSUE THREAD

**Issue by woody166** [joBr99/nspanel-lovelace-ui#172]
Hi,

Is it possible to play audio/rttl files on the internal speaker via tasmote/mqtt requests, I know rttl can be played when flashed with ESPHome but is this possible with tasmota?

If so could this be added in future release?

**Comment by joBr99** [comment]
This is outside of scope of this firmware, because it's a tasmota Feature, no clue if you can play rttl on it, it's controlled with the buzzer command

https://tasmota.github.io/docs/Buzzer/

If you want to use esphome for this specific feature, take a look at this project:

https://github.com/sairon/esphome-nspanel-lovelace-ui

**Comment by woody166** [comment]
Thanks for the feedback Johannes.

It's not something that I want that'll make me change from the absolutely awesome work you've done on this.
