### ISSUE TITLE
[Feature Request] Edge Swipe gestures for page navigation

### ISSUE THREAD

**Issue by matrixx567** [joBr99/nspanel-lovelace-ui#182]
Hy,
thank you for this incredible project. It works like a charm and I really love it.

Are there any plans to integrate swipe gestures for navigation between pages (left, right, up).

In the repo https://github.com/krizkontrolz/Home-Assistant-nextion_handler/tree/main/Tips_and_Tricks two ways for swipe gestures are shown and described in detail with an example implementation.

Thanks in advance.

**Comment by joBr99** [comment]
I guess the descibed edge swipes would work, but it kina counter intuitive that you have to do a complete swipe from one edge to another, this is something you usally don't have on other devices (especially without animations)

The display in the nspanel has no native support for gestures, you have to implement it yourself, which is only possible for pages without other UI controls like the home screen on the stock fw.
Didn't see the stock fw for a long time, but if I remember correctly they only have swipe support on their home screen.

For pages with a ton of UI controlls you will end up with unintentional button presses or with really unreliable swipe support, because it doesn't work if you start or end on a ui element.

See #55 and #6 for more details on swipe, there was a debug page with swipe support in the firmware, if you want to try yourself I can get you the export of this page which you can import and then copy paste the code to different page.

**Comment by jhmcgilljr** [comment]
Any way to create a swipe up action from the bottom?  Perhaps to return to screensaver or navigate to default card?  While I realize there are no other buttons for this existing, it would be a nice feature to have a universal action available from all screens that could call a configurable function...

Should I create a new enhancement request for this if there is not a current way to implement it?
