### ISSUE TITLE
[Feature Request] Meida card Power button Colored when on 

### ISSUE THREAD

**Issue by kroon040** [joBr99/nspanel-lovelace-ui#236]
I'd love to have in the media card, that when the device is on, it's colored. Maybe orange also a the volume slider as in screenshot below.
And also the power button as volume slide same color?
 
![media](https://user-images.githubusercontent.com/40452265/170862083-0fbd7fe4-cd73-46c6-9071-ca78d94576c9.png)

Panel EU

Now it looks like this on the panel, the power button is white
![media](https://user-images.githubusercontent.com/40452265/170862152-6fef3206-0933-4cfa-a90d-c3db069461f0.jpeg)

**Comment by joBr99** [comment]
https://github.com/joBr99/nspanel-lovelace-ui/blob/9e89a549dbab235f7539fd1b24ac1a19b3cd2ea2/apps/nspanel-lovelace-ui/luibackend/pages.py#L362

I don't have a media device with the power on/off feature, changing this color is easy. The color of the volume slider chnnot be changed dynamicly, because it's a picture.

**Comment by joBr99** [comment]
color changed

https://github.com/joBr99/nspanel-lovelace-ui/commit/574cf25c7413fafdf27e93283c5d1ab8f2a60479

**Comment by kroon040** [comment]
Nice  the button has now a nice color, A bit pitty that the slider can't be the same color
