### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by janprive** [joBr99/nspanel-lovelace-ui#340]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

I have several RaspberryPi’s with Hyperpixel touchscreen. Is there a way to emulate the Nspanel screen? Or the hmi-code? Some kind of Chrome extension? Currently I use them with Chrome in kios-mode and appdaemon as a dashboard. 

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
No, there is only the crappy nextion editor, which only runs on Windows.

I would just open the native Homeassistant dashboard on the raspberry.

I can recommend you unofficialnextion.com for nextion related questions, but there won't be a way to emulate it on linux, because nextion don't want their users to use nextion editor on linux, they even called that there are only illegal use cases on linux somewhere.

**Comment by MMMZZZZ** [comment]
I'd like to add: "illegal" in their eyes. But perfectly legal by the laws of most countries (AFAIK; not a lawyer).

Kind regards,
Max
