### ISSUE TITLE
[Feature Request] [iobroker] Additional infos on Subpage

### ISSUE THREAD

**Issue by kuckuckmann** [joBr99/nspanel-lovelace-ui#350]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Pre-description:
If using a card with "type": "cardEntities" for control switches like a lamp, then on clicking the text a subpage is displayed which is currently only showing the switch button.

Suggestion: 
Display several information which can be defined within an alias.
For Example: If configuring a Lamp with ON/OFF switch, used power data (overall) current power usage, etc.
Maybe a screenshot can explain it much better:

![grafik](https://user-images.githubusercontent.com/99131208/178783560-bbaa71cd-5206-4d50-b5e6-cb34701e408d.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

I am using EU Panel with Tasmota 11 and TFT-Firmware 3.1.1

**Comment by joBr99** [comment]
@Armilar 
Is there a difference between lights and switches in the ioBroker implementation? (and also are there different alias types for lights and switches)

In the firmware are two different types of switches "light" and "switch", the main difference is that with the light type it's possible to open that detail page (which contains a lot of controls for color brightness and color temperature, so there is not really a space to fit such information)

```
        if entityType in "light":
            return f"~light~{entityId}~{icon_id}~{icon_color}~{name}~{switch_val}"
        if entityType in ["switch", "input_boolean", "automation", "fan"]:
            return f"~switch~{entityId}~{icon_id}~{icon_color}~{name}~{switch_val}"
```
However it's possible to display text/sensors on the cardEnties page aswell as on cardGird (it's possible to show numbers instead of icons there) with the firmware.

![image](https://user-images.githubusercontent.com/29555657/178788420-a4a82fc0-2017-4a21-b19f-c83f04128123.png)

**Comment by Armilar** [comment]
No, we currently do not differentiate between light and switch. There are actually only two different alias types that can be chosen, but do not have to be. If the socket alias is selected, then the icon is not a lamp but a switch. But we can now give any imaginable icon. Even separated for on/off.

But it would only take 2 minutes to give the alias switch the type Switch in the TypeScript

**Comment by Armilar** [comment]
I personally don't need it either.

**Comment by joBr99** [comment]
You are right, adding a second line to the light page requires also to move the header itself, which will cause it to look non centered anymore. It should be possible to modify the Label of the Color Wheel Icon, so it can be used without showing the color wheel itself, with the other label's this won't work, because they have to change visibilty based on the light type. So this is also not really a solution.

![image](https://user-images.githubusercontent.com/29555657/183312040-c5936598-4847-4616-8926-da40e2dec19c.png)
