### ISSUE TITLE
[Feature Request] Have Lovelace work with OpenHAB

### ISSUE THREAD

**Issue by Knuppel1983** [joBr99/nspanel-lovelace-ui#362]
### FEATURE DESCRIPTION
Have this beautiful UI work with OpenHAB.

### ADDITIONAL CONTEXT
There is an NxPanel version for Openhab, which works by running a rule that fires a Groovy script. This script then sends back the panels based on the requested panel number. But NxPanel's UI is less attractive, and your panels seem to accomodate more room for text descriptions (vertical lists). And it just looks more finished. Is it possible to adapt it to OpenHAB and write a tutorial howto?

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Hey, 
this is out of scope for me since I'm not using openhab, however it's definitly possible.

britzelpuf and Armilar continued an ioBroker backend for this HMI/UI

If you are going to start implementing an openhab backend I will definitly help you getting started and I will answer you questions about the command structure, but I won't implement it.

documentation of the serial commands of the firmware is here: https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI

The picture is from a really early version, so the commands changed, but it still points out the príncipe used.

**Comment by Knuppel1983** [comment]
> Hey, this is out of scope for me since I'm not using openhab, however it's definitly possible.
> 
> britzelpuf and Armilar continued an ioBroker backend for this HMI/UI
> 
> If you are going to start implementing an openhab backend I will definitly help you getting started and I will answer you questions about the command structure, but I won't implement it.
> 
> documentation of the serial commands of the firmware is here: https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI
> 
> The picture is from a really early version, so the commands changed, but it still points out the príncipe used.

Thanks. The ioBroker Javascript would seem like the easiest route and would only require referencing OpenHAB items/devices instead of ioBroker ones. Unfortunately my knowledge of Javascript is limited.
