### ISSUE TITLE
[Help] Uninstall / Return to Stock

### ISSUE THREAD

**Issue by ahorseman** [joBr99/nspanel-lovelace-ui#436]
Hello,

I've desparately tried to get Lovelace UI on my NSPanel work with OpenHAB but had no luck at all.

Hence, I want to switch back to the stock UI, which had at least some value on the default screen for me that I could control through Tasmota (i.e., temperature and clock) and especially, the display wasn't on all the time.

I unfortunately couldn't find documentation of how to revert to stock from Lovelace. Can you please either point me to that documentation or give some hint, how to get back to stock?

Thanks a lot in advance.

**Comment by joBr99** [comment]
Did you try to implement a backend for lovelace in OpenHab?

It is possible to revert back to stock, I can help you to do so, if you want to implement a backend for this firmware I can also help you with that.

**Comment by ahorseman** [comment]
Unfortunately I do not have the time anymore to do so... I am living off of the stuff I did during my studies and that I have at hand, like my OpenHAB installation and knowledge about setting it up and configuring, flashing ESP32, etc... So flashing Tasmota, etc. is things I've done before and which is done in couples of minutes for me. Writing a backend for OpenHAB is something I've never done and won't have time to get into reading all the documentation and catching up, unfortunately. I hoped this could be simply controlled through MQTT (like sending some JSON to an endpoint, which I'd then been doing through OpenHAB rules) or via Tasmota console, but it seems it's more sophisticated.

So if you have a file that needs to be flashed to revert to stock firmware that would be great and I'd appreciate that a lot.

**Comment by joBr99** [comment]
Well, the firmware is controlled though MQTT Commands, they are not json and the display doesn't keep any config, but once you have a basic understanding of the protocol it is straight forward.  The the amount of work always depends on how many features you want to implement/use.

See theese messages for getting started with it:

Message vom Screen in Loading Screen
`event,startup,39,eu` to RESULT topic

Answer from the backend to the CustomSend MQTT Topic (You can also send thoose messages as command on tasmota console for testing)

`time~18:17`
`date~Donnerstag, 25. August 2022`
`timeout~20`
`dimmode~10~100~6371` 

touching the panel on the screensaver will result in this MQTT Message on the result topic:

`event,buttonPress2,screensaver,bExit,1`

you can answer this by sending theese commands to the CustomSend Topic

`pageType~cardEntities`

`entityUpd~test~1|1~light~light.schreibtischlampe~X~17299~Schreibtischlampe~0~text~sensor.server_energy_power~Y~17299~Server ENERGY Power~155 W~shutter~cover.rolladenfenster_cover_1~Z~17299~Fenster Eingang~A|B|C|disable|enable|enable~switch~switch.bad~D~63142~Bad~1`

-------------------------------

The stock firmware is linked for example here:

https://github.com/masto/NSPanel-Demo-Files/issues/4

You need to put it on an HTTP (not HTTPS) and then run the FlashNextion Command in Tasmota Console with the URL of the tft file. (Don't use the build-in webserver of OpenHAB if I remember correctly it did some wired non standard stuff and doesn't work, because it doesn't provide a content length header)

**Comment by ahorseman** [comment]
Hello @joBr99,

thanks for the extensive reply. Hmmm... if there's an "API" documentation, i.e., explanation that details systematically what to send to the panel, I might think about that when having vacation. I just cannot put a lot of effort into it. I will try out the CustomSend ... commands in Console to see what happens. I would already be happy to just display the current time and to have it turn off after 30 seconds to save energy. I assume there's nowhere some tutorial or blog talking about this topic, yet?

Thanks again and I will check those commands, though I assume for the moment I might revert to stock to have it at least work with minimal features that are provided in stock.

**Comment by joBr99** [comment]
The serial commands are listed here, but this only helps you after you've understood the protocol and worked with it.

Hit me up on Unoffical Nextion Discord and I will provide you examples for the stuff you want to do.

**Comment by ahorseman** [comment]
Hello @joBr99,

thanks a lot for your explanation. I indeed managed to turn off the screen and write some hello world on the display. However, the weather stuff for instance, just seemed to reveal text and not really information.

For now, I'm reverting to stock NSPanel (especially, so the screen is not on 24/7) and will try to get back to this, once i have some more time. :(

But thank you very much for your help. If you should have some blog or some resource pop up, where somebody describes useful examples and shares knowledge, please let me know here, so I can give it another shot.

All the best!

**Comment by joBr99** [comment]
I didn't provide an example for the weatherupdate.

Take this as an exmaple:

`weatherUpdate~X~27.1C~Fr.~Y~29.3C~Sa.~Z~25.4C~So.~A~24.1C~Mo.~B~23.8C~~`

**Comment by joBr99** [comment]
It doesn't make a lot of sense for me to blog about this, the audience for this is really limited. 
If somebody is implementing a backend for this panel and needs examples for the serial protocol I'm providing personal assistance to them. This is something way more helpful than providing more documentation and exmaples about it.
