### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by uros76** [joBr99/nspanel-lovelace-ui#598]
### PROBLEM DESCRIPTION
After loading the latest tasmota firmware on my nspanel and then autexec.be from this repo, I tried to load the latest screen tft from here. Unfortunately, when I run the command `FlashNextion http://nspanel.pky.eu/lui-release.tft` through tasmota console I get the error shown below under the screenshot section. 
I don't know what else to do, seems like screen is stuck? I checked the error text in autoexec.be file but I still can't figure out what it is or what should I try differently. I have not even gone to homeassistant part of the configuration yet. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/25409772/204367022-437f97e8-03fe-43d3-b954-949ffbf11e5a.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU version with Tasmota: 
Program Version | 12.2.0.5(nspanel)
2022-11-28T11:36:15
2_0_5_3/v4.4.3

**Comment by joBr99** [comment]
I cannot really tell you what's going on there and I would like to have a look by myself.

Please contact me on nextion discord:
https://unofficialnextion.com/t/welcome-to-the-unofficial-nextion-tjc-user-forum/8

**Comment by uros76** [comment]
Thanks for the help. With slower flashing speed it worked

**Comment by nicop4** [comment]
@uros76 can you share your fix ? I have a similar issue I cannot upload the display firmware

**Comment by joBr99** [comment]
What do you mean with similar? 
What issue do you have?
Is the flashing screen coming up?
Which tasmota version are you on?

**Comment by nicop4** [comment]
Hi @joBr99 !

I'm using Tasmota 12.2.0.5.

At first I could not get the screen to flash (nothing happened, I was still on the out of the box display) and as it was my first experience with the nspanel and nextion screen I didn't know what to expect.

But after investigations I concluded that the screen connector was in fault (because I unplugged it to solder serial wires on the PCB), and after that I could start the screen flash process but never transfered any byte. After a reboot the screen was bricked with the message "System data ERROR!"

Initially I used the [berry driver](https://github.com/joBr99/nspanel-lovelace-ui/blob/main/tasmota/autoexec.be) found on [this page](https://docs.nspanel.pky.eu/prepare_nspanel/#flash-firmware-to-nextion-screen) and the flashing process would never start and so I bricked the screen. 

I tried different versions of the berry driver but without success. And finally I tried with the version you linked here and it worked ! So I assume this version fixed the issue, although there is a tiny chance that the screen connector moved a bit and now works but I dont believe it.

I would suggest to add information in documentation of nspanel lovelace UI about the "risks" of a bad screen connection.
And in the ["Flash Firmware to Nextion Screen"](https://docs.nspanel.pky.eu/prepare_nspanel/#flash-firmware-to-nextion-screen) to specify that the `FlashNextion` command has to be typed in the tasmota console and not in the berry console (it was confusing for me because just before we need to flash the berry driver :) ), plus what to expect on the screen and in the console when it works properly (or when it does not work) because as the command was accepted I though it was OK (even if it was quick...)
And may be checking if all the links for berry driver are the good version on the [NsPanel Lovelace UI Docs page](https://docs.nspanel.pky.eu/prepare_nspanel/).

Thanks again for your work and your help, I will continue with my customizations.

**Comment by joBr99** [comment]
>I'm using Tasmota 12.2.0.5.

There was an issue with Tasmota and the flashing of the berry driver with Tasmota 12.2.0.4 and 12.2.0.5, which is now fixed. How did you flash Tasmota to the Panel? 

Did you use the Webinstaller?

12.2.0 is the latest release of tasmota on github aswell as on the firmware page (http://ota.tasmota.com/tasmota32/release/), 12.2.0.5 should be development version of tasmota.

> After a reboot the screen was bricked with the message "System data ERROR!"

There is not really a way to brick the screen ;) Worst thing that can happen is the System Data ERROR and you can just start over with the flashing.

> And may be checking if all the links for berry driver are the good version on the [NsPanel Lovelace UI Docs page](https://docs.nspanel.pky.eu/prepare_nspanel/).

There is only one link to the driver, always the latest version.

**Comment by nicop4** [comment]
> Did you use the Webinstaller?

I did use WebInstaller yes.

> There is not really a way to brick the screen ;) Worst thing that can happen is the System Data ERROR and you can just start over with the flashing.

And yes indeed with a new flash of the screen we recover from this problem, but I had a "working" nspanel, and after just an error message on the screen ^^ 
Tasmota and the hardware buttons were still working of course.

> There is only one link to the driver, always the latest version. New versions are installed through the AppDaemon Backend.

mmm.. t seemed to me that the filesize was different. This file was the file I downloaded, I might have done an error on my side though.
[autoexec.be_used.txt](https://github.com/joBr99/nspanel-lovelace-ui/files/10127579/autoexec.be_used.txt)

**Comment by joBr99** [comment]
No, you just installed/downloaded the autoexec.be file before that bug was fixed.

https://github.com/joBr99/nspanel-lovelace-ui/commit/89d5d3f47cd7a00ff41a5a9523d1d2c172cddf0d

#601

**Comment by nicop4** [comment]
And another warning, the wires I soldered to flash tasmota left a small blob of solder after removing them, causing a short with the back of the screen when the panel was fully reassembled.
The screen was on, but ESP board was not booting.

**Comment by joBr99** [comment]
You usally don't have to solder wires to devices like this  (or at least I don't)

Just use some male jumper cables and hold them in the correct position until you finsihed flashing :)

**Comment by nicop4** [comment]
> No, you just installed/downloaded the autoexec.be file before that bug was fixed.

Bummer >_<

Anyways thanks for the help and analysis, I'm good to go :)

**Comment by nicop4** [comment]
> You usally don't have to solder wires to devices like this (or at least I don't)
> 
> Just use some male jumper cables and hold them in the correct position until you finsihed flashing :)

You're right that's absolutely sufficient, I wanted to listen the serial port once started to debug if needed and because I'm curious, so it was more "reliable" with soldered wires.
