### ISSUE TITLE
[Feature Request] Add support for groups (lights or switches)

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#709]
### FEATURE DESCRIPTION
Please add support for groups. Now groups of lights or switches (of both combined) are not supported. I'd like to have a botton on the display to control all the lights in a group at once, just like a single lightbulb.

### ADDITIONAL CONTEXT
n/a

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
See #319

Groups are supported, however only the newer groups.

(Their entity name starts with light or switch instead of group)

The old style groups are no longer recommended to use anyways, see HA Documentation, you can create them through the UI and with yaml as well.

https://www.home-assistant.io/integrations/group/

**Comment by EddyK69** [comment]
Sorry, I missed that one somehow. Thx!!

**Comment by BlueManRising** [comment]
I am trying to do a group for some window blinds, i created a "group" in HA and its specially a cover group, name is : cover.(groupnamehere) but the NSPanel does not recognize, did I set it up incorrectly?

**Comment by joBr99** [comment]
No, sounds like it should work

**Comment by BlueManRising** [comment]
Quick HA restart, and yep, sure does work! AMAZING!!
