### ISSUE TITLE
[Feature Request] Support templates to render entity icons in Power Card

### ISSUE THREAD

**Issue by magnusoverli** [joBr99/nspanel-lovelace-ui#721]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._
Adding support to render entity icons, the same way templates are supported for setting the speed parameter for entities represented in the Power Card
### ADDITIONAL CONTEXT
_Add any other context about the problem here._
Example of possible config:
```
      - type: cardPower
        title: ""
        key: power
        entities:
          - entity: sensor.ams_power_active
            icon: home-lightning-bolt-outline
            color: [255,255,251]
            title: Total
          - entity: delete
          - entity: sensor.hvac_sensor_active_power
            icon: >-
              {% if states('sensor.hvac_sensor_active_power') | int >= 40 %}
                mdi:radiator
              {% elif states('sensor.hvac_sensor_active_power') | int <= 39 %}
                mdi:radiator-off
              {%endif%}
            color: [255,255,251]
            speed: >-
              {% set entity_power = states('sensor.hvac_sensor_active_power') |float | round(3)%}
              {% set total_power = states('sensor.ams_power_active') | float | round(3) %}
              {% set entity_usage = (entity_power / total_power) * 100 | float | round(3) %}
              {{ (entity_usage | round()) * -1 }}
```
### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
hey icons and templates are a litte bit different, because you can have different "prefixes"

without an prefix it's assuming that you acually wanted to have an icon so the following two are the same (execpt for the nice icon in vscode on the second)

`icon: lock`
`icon: mdi:lock`

this will display AbC

`icon: txt:AbC`

and `ha: something` will be rendered as template (never tested with multiline, but that should also work)

`ha:{{% if states('sensor.hvac_sensor_active_power') | int >= 40 %}{% elif states('sensor.hvac_sensor_active_power') | int <= 39 %}{%endif%}}`

The only downside of this is that you cannot use the names of the icons, you need to use the acual char. You can get the char by clicking the U on the cheatsheet.

https://docs.nspanel.pky.eu/icon-cheatsheet.html

**Comment by magnusoverli** [comment]
Right, didn't know that. :-) Nice trick!!
Still, I don't see then why my template should not work, so long as multiline is working.
I cannot get your example to render an icon either...?

**Comment by joBr99** [comment]
try this one:

```
            icon: "ha:{% if states('sensor.today_energy') | int >= 40 %}{% elif states('sensor.today_energy') | int <= 39 %}{%endif%}"
```

**Comment by joBr99** [comment]
added a new icon type `ha-i`, so you can use the mdi name instead of the acual char, which should also fix the issue with radiator icon being broken after going though the template

**Comment by Tedo-63** [comment]
I tried this command

        icon: "ha-i:{% if(states('input_boolean.distrib_lettre') == 'on' %} mdi:email {% else %} mdi:package {% endif %}"

but I don't have any icon display. Can you tell me how to proceed. 
best regards
