### ISSUE TITLE
[Feature Request] Rate limiting on Power Card

### ISSUE THREAD

**Issue by duanemck** [joBr99/nspanel-lovelace-ui#738]
### FEATURE DESCRIPTION
_A clear and concise description of what the feature should do._

Would it be possible to configure some sort of rate limit on the Power Card, with 8 rapidly changing entities it seems to put a bit of strain on the ESP/Nextion (not sure where). The screen becomes unresponsive. If I tap a navigation button I need to wait sometimes 10seconds for it to be processed. In frustration I will tap it multiple times which seem to be queued up and then executed in rapid succession once the card closes.

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

3.9.3
US-P but would probably be applicable to all.

**Comment by joBr99** [comment]
implemented a cooldown options for the cards
https://github.com/joBr99/nspanel-lovelace-ui/commit/87fca788a68753200803365e681c82e51abf17d1


```
      - type: cardPower
        cooldown: 0.5
        entities:
```

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

The question for the version of the panel is mostly because there are usally things broken in US-P/US-L during development :)
Try to update the backend and the firmware to the development version, US-P and EU is currently working; in US-L the Power Card is broken.

I didn't do extensive testing with it, only tried with a light on a cardGird, so please let me know if it's working.

**Comment by duanemck** [comment]
Thank you, will update to the dev version a bit later and give it a try. 
Just to make sure I understand correctly, in your example above, the card will only be updated every 0.5 seconds? 
So I could slow it down a lot by doing something like `cooldown: 5` ?

**Comment by joBr99** [comment]
Yes it should be in seconds
