### ISSUE TITLE
[BUG] iobroker Error if the js-global-script is executed

### ISSUE THREAD

**Issue by Missenberger79** [joBr99/nspanel-lovelace-ui#765]
After I could not interpret various error messages with the existing global TS script, because the panel worked fine and the errors occurred in other scripts, I read here that with the js global script. 

Most of the error messages are now gone with the js-script but with the sonos http api script I still get the following message when the global script is executed:

`error Error in request callback: ReferenceError: forceCreate is not defined`

If i return the "use strict" there is no error messages anymore. Dif i have another problem without "Use strict"

I got the script from [https://github.com/dwm66/iobroker-scripts/blob/master/SonosAPI/sonosapi.js]()

**Comment by Armilar** [comment]
I once removed the "bug" because it is not a bug for me if another global script causes an error.

Just so we understand each other correctly. The TypeScript "NsPanelTs.ts" is not a global script, but a local script. Only the TypeScript "icon_mapping.ts" has to be created in the global folder, since it can be used for all panels and is imported by the "NsPanelTs.ts" at runtime.

The question now arises: Why is the Sonos JavaScript: https://github.com/dwm66/iobroker-scripts/blob/master/SonosAPI/sonosapi.js created as a global script? As a rule, global scripts in ioBroker are appended before all other scripts. Of course, this can lead to nasty errors if the same variables, constants or function definitions are used. Especially when there are very long scripts.

So, if one of the two scripts sonosapi.js or NSPanel.ts ended up in the global script folder, please change that by moving both scripts to the local area.

If there are still errors in the log, please describe them under: https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui/2147?_=1676223401632 and click on reply...

**Comment by Missenberger79** [comment]
Only the script for the icon_Maping is created as a Global Scricpt.

The other two scripts for "Sonos-http-API" and for the nspanel are created as "local" scripts.

If in the global icon_Mapping Javascript the "use strict" is used, then the error comes from the Sonos Script.

What I do not understand, if in a global script a "use strict" is used, this is then also applied in all local scripts.

I have commented out the use strict line and after that it works. Can without the line another misbehavior arise?

**Comment by Armilar** [comment]
In "strict mode" (use strict) JavaScript does not allow the use of variables until they are declared. That's all.

What problems arise in the area of comprehensive or global scripts, you should ask the ioBroker core team.

**Comment by joBr99** [comment]
@Armilar

Wenn die globalen Skripte einfach nur vor alle anderen Skript gepacket werden, dann fliegen einem alle ranz Skripte um die Ohren, die nicht im strict mode laufen, weil in dem icon_mapping.js ganz oben "use strict" drin steht.

**Comment by Armilar** [comment]
Ups ;-)

das icon_mapping.js sollte gar nicht mehr genutzt werden, seitdem der TypeScript-Bug im Javascript Adapter vor mehreren Wochen behoben wurde.

Ich denke ich entferne das mal aus den Anleitungen...

Im icon_mapping.ts , welches genutzt werden sollte ist kein "use strict" drin.
