### ISSUE TITLE
[BUG] HMI cardGrid should implement popups as in cardEntities

### ISSUE THREAD

**Issue by laluz742** [joBr99/nspanel-lovelace-ui#854]
`cardGrid` just handles poups for types `shutter`, `input_sel` and `timer`
Should support popups for entity types
- `light` -> `page popupLight`
- `fan`-> `page popupFan`
on touch press events of tEntity1 .. tEntity6

**Comment by joBr99** [comment]
It does, just do a long press on the button

**Comment by laluz742** [comment]
So what's the deal having popups behave differently? (press vs long press)

**Comment by joBr99** [comment]
short press on cardgrid is always `event,buttonPress2,internalNameEntity,button` to togge the state of the entiy, on some types like light you can open the detail page with a long press and on some types the short press doesn't make sense because it's unclear what it should do (shutter, input_sel and timer) and it will go directly to the detail page
